config/routes.rb
EvolvingFinal::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } 


  root to: 'pages#home'
  resources :admins
  resources :users
 
  resources :books do
     resources :snippets, :only => [:create, :edit, :update, :destroy]
  end
  

  #get 'sign_in', :to => 'users/sessions#new', :as => :new_session
  post "books/:id/activate" => "books#approve", :as => "active_book"
  post "snippets/:id/activate" => "snippets#approve", :as => "active_snippet"

  put "books/:book_id/like", to: "books#upvote", :as => "book_like"
  put "books/:book_id/dislike", to: "books#downvote", :as => "book_dislike"
 

end

app/views/admins/_snippet.html.erb
<% @snippets.each do |snippet| %>

            
                <%= raw(snippet.content)  %>

                <% if can? :manage, snippet %>
                <%= link_to 'delete', active_snippet_path(snippet.id), :method => :delete %>
              <% end %>

   
       
<% end %>

app/views/admins/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.profile_name, '#' %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.full_name.titleize unless user.full_name.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.rank %>" class="btn btn-mini" type="button">Change rank</a>
          <% render 'admins/user' %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</div>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Book Title</th>
      <th>Book Created</th>
      <th>Registered</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book %></td>
      <td><%= book.created_at.to_date %></td>
      <td><%= %></td>
      <td>Status</td>
<td><%= button_to 'Approve', active_book_path(book) %></td>
</tr>
       
    </tr>
  <% end %>
  </tbody>
  </div>
  
  <div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Book Created</th>
      <th>Content</th>
      <th>Link to Book</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @snippets.each do |snippet| %>
    <tr>
      <td></td>
      <td><%= snippet.created_at.to_date %></td>
      <td><%= render 'admins/snippet' %></td> 
      <td><%= link_to snippet.book.title, book_path(snippet.book) %>
      <td>Status</td>
<td><%= button_to 'Approve', active_snippet_path(snippet.id) %></td>
</tr>
       
    </tr>
  <% end %>
  </tbody>
  </div>

app/views/admins/show.html.erb
<h3>User</h3>
<p>User: <%= @user.full_name %></p>
<p>Email: <%= @user.email if @user.email %></p>