config/routes.rb
EvolvingFinal::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } 


  root to: 'pages#home'
  resources :admins
  resources :users
 
  resources :books do
     resources :snippets, :only => [:create, :edit, :update, :destroy]
  end
  

  #get 'sign_in', :to => 'users/sessions#new', :as => :new_session
  post "books/:id/activate" => "books#approve", :as => "active_book"
  post "snippets/:id/activate" => "snippets#approve", :as => "active_snippet"

  put "books/:book_id/like", to: "books#upvote", :as => "book_like"
  put "books/:book_id/dislike", to: "books#downvote", :as => "book_dislike"
 

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  include ActionView::Helpers::SanitizeHelper 
  after_update :update_user_rank
  belongs_to :book
  belongs_to :user
  attr_accessible :content, :book_id , :approved, :user_id
  attr_reader :info_panel_words
  validate :stop_create, :on => :create
  validates :book_id, presence: true
  validate :size_limit

  def stop_create
    errors.add(:base, "could not add due to last snippet not approved") if Snippet.last.try(:approved) == false
   end
   
  def update_user_rank
    user.user_rank
  end 
   
self.default_scope order('created_at ASC')
 

 scope :approved, -> { where(approved: true) }



  BOOK_SIZE = { 
    0 => {'per' => 500, 'total' => 15000},
    1 => {'per' => 700 , 'total' => 30000},
    2 => {'per' => 1000, 'total' => 50000}
  }
  
  def info_panel_words(snippet)
      stripped_content = strip_tags(content)
      word_count = stripped_content.scan(/\w+/).size.to_i
      current_size = (self.book.title_count || 0) + word_count
  end

   def size_limit 
    stripped_content = strip_tags(content)
    book_limit = self.book.size.to_i
    word_count = stripped_content.scan(/\w+/).size.to_i
    current_snippets_size = (self.book.get_word_count || 0) + word_count 
    errors.add(:base, "Content size is too big") unless word_count < BOOK_SIZE[book_limit]['per'] && current_snippets_size < BOOK_SIZE[book_limit]['total']    
  end

 def self.newest
  Snippet.order('created_at DESC').limit(5).all
  end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
load_and_authorize_resource
  before_filter :authenticate_user!
  before_filter :find_book, :except => [:approve]
  
   def create
    binding.pry
   @snippet = @book.snippets.create(snip_params)
   @snippet.user = current_user
     if @snippet.save
      redirect_to @book
      flash[:success] = "Snippet submitted and awaiting approval."
    else
      flash[:base] = "Someone else has submitted a snippet, please try again later"
      redirect_to @book
   end
 end

  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end     
  
  def approve

      @snippet = Snippet.find(params[:id])
    if @snippet.update_attribute(:approved, true)
      redirect_to admins_path
    else
    render root_path
   end 
  end

  def edit
    @snippet = @book.snippets.find(params[:id])
  end    
  
  def update
    @snippet = @book.snippets.find(params[:id])
    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to @book, notice: 'Comment was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  private

  def find_book
    #raise params.inspect
    @book = Book.find(params[:book_id])
  end

  def snip_params
      params.require(:snippet).permit(:content, :approved, :user_id)
    end
end
  

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/_form.html.erb

<%= form_for([@book, @snippet]) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.text_field :content, class: 'wysihtml5', :cols => "60", :rows => "10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snippets/_snippet.html.erb
<% @snippets.each do |snippet| %>

            
                <%= raw(snippet.content)  %>

                <% if can? :manage, snippet %>
                <%= link_to 'delete', book_snippet_path(@book, snippet), :method => :delete, :class => 'btn-small btn-color' %>
              <% end %>

   
       
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing Snippets</h1>
<%= form_for @snippet, :url => book_snippet_path(@book, @snippet), :html => {:method => :put} do |f| %>
<%= render 'form' %>
<% end %>



