config/routes.rb
EvolvingFinal::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } 


  root to: 'pages#home'
  resources :admins
  resources :users
 
  resources :books do
     resources :snippets, :only => [:create, :edit, :update, :destroy]
  end
  

  #get 'sign_in', :to => 'users/sessions#new', :as => :new_session
  post "books/:id/activate" => "books#approve", :as => "active_book"
  post "snippets/:id/activate" => "snippets#approve", :as => "active_snippet"

  put "books/:book_id/like", to: "books#upvote", :as => "book_like"
  put "books/:book_id/dislike", to: "books#downvote", :as => "book_dislike"
 

end

app/models/book.rb
class Book < ActiveRecord::Base
  include ActionView::Helpers::SanitizeHelper 
  acts_as_votable
  after_update :update_user_rank
  has_many :snippets 
  belongs_to :user
  #attr_accessible :title, :book_id, :size, :cat, :approved, 
   #               :user_id, :votable, :voter, :vote_scope

  validates :title, presence: true,
                    uniqueness: true
  validates :size, presence: true
  validates :cat, presence: true
  scope :approved, -> { where(approved: true) }
  
  def self.newest
  Book.order('created_at DESC').limit(5).all
  end
  
  def title_count
    stripped_tags = strip_tags(title)
    word_count = stripped_tags.scan(/\w+/).size.to_i
  end

   def update_user_rank
    user.user_rank
   end 

  def get_word_count
    @word_count = []
    self.snippets.each do |c|
      stripped_tags = strip_tags(c.content)
      @word_count << stripped_tags.scan(/\w+/).size.to_i
    end
    @word_count = @word_count.inject(:+)
  end
 
  def short?
   size == 0
  end
  
  def medium?
    size == 1
  end
  
  def long?
    size == 2
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy ]
  
  #before_action :content_check
  # GET /books
  # GET /books.json
  def index
     @books = Book.where(approved: true)
     @books = @books.where(:cat => params[:cat]) if params[:cat]   
     @snippets = Snippet.where(approved: true)
  end
  
  def approve
     @book = Book.find(params[:id])
    if @book.update_attribute(:approved, true)
      redirect_to admins_path
    else
    render root_path
   end 
end

  # GET /books/1
  # GET /books/1.json
  def show
    if Book.where(approved: true)
    @book = Book.find(params[:id])
    @snippets = @book.snippets.where(approved: true).paginate(:page => params[:page], :per_page => 10)
    @snippet = @book.snippets.new
    @count = @snippets.map {|e| e.info_panel_words(@book).to_i }
    @count = @count.inject(:+)
    else
      redirect_to root_path
      flash[:alert] = "Submitted for approval."
    end
  end

  # GET /books/new
  def new
    @book = Book.new
    
  end

  # GET /books/1/edit
  def edit
  end
  
  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully submitted for approval.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

def upvote
 raise book_params.inspect
  @book = Book.find(params[:id])
  @book.liked_by current_user(book_params)
  redirect_to books_path
end

def downvote
  @book = Book.find(params[:book_id])
  @book.downvote_from current_user
  redirect_to books_path
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :size, :cat, :user_id, :votable, :voter, :vote_scope
)
    end
end

app/helpers/books_helper.rb
module BooksHelper


end

app/views/books/_form.html.erb
<%= simple_form_for(@book, :html => { :class => 'form-horizontal' })  do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
    <ul>
     
    <li><%= f.label "Book Title" %></li>
    <li><%= f.input :title, label: false,  input_html: { :style=> 'width: 250px'}%></li>
    <li><%=f.input :size, input_html: {:style=> 'width: 120px'}, collection: [['Short', 0], ['Medium', 1], ['Long', 2]], :class => 'dropdown-toggle' %></li>
    <li><%=f.input :cat, input_html: { :style=> 'width: 120px'}, collection: [['Sci-Fi', 'Sci-Fi'], ['Thriller', 'Thriller'], ['Romance', 'Romance'], ['Action', 'Action'], ['Crime', 'Crime']], :class => 'dropdown-toggle' %></li>
    <br />
    <li><%= f.button :submit, "Create the book", :class => 'btn green large' %></li>
    </ul>

 <% end %>

app/views/books/_snippetnew.html.erb
 <%= simple_form_for [@book, @snippet] do |f| %>

        <p>

         <%= f.input :content, :as => :ckeditor, :label => false, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>

        </p>
         <%= f.submit "Create Snippet" %></p>
    <% end %>
 <% else %>
  <h1>POOP</h1>

<% end %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
</div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<%= render 'pages/sidebar' %>
<link href='http://fonts.googleapis.com/css?family=Vast+Shadow' rel='stylesheet' type='text/css'>
 <div class="posts-block col-lg-9 col-md-9 col-sm-8 col-xs-12">
                       
                        <article class="post hentry">
                           <% @books.each do |book| %>
                           <header class="post-header">
                              <h3 class="content-title"><%= book.title %></h3>
                                  <%=link_to book_like_path(book), :method => :put do %>
                                 <i class="icon-thumbs-up">Like</i> 
                                  <% end %>
                                  <%=link_to book_dislike_path(book.id) do %>
                                      <i class="icon-thumbs-down">Dislike</i>
                                  <% end %>

                              
                                  
                              <div class="blog-entry-meta">
                                 <div class="blog-entry-meta-date">
                                    <i class="icon-time"></i>
                                   <%= book.created_at.to_s(:create_date) %>
                                 </div>
                                 <div class="blog-entry-meta-author">
                                    <i class="icon-user"></i>
                                    <%= book.user.full_name %></a>
                                 </div>
                                 <div class="blog-entry-meta-tags">
                                    <i class="icon-tags"></i>
                                    <%= book.cat %>
                                 </div>
                                 <div class="blog-entry-meta-comments">
                                    <i class="icon-comments"></i>
                                    <%= pluralize(book.snippets.count, "Snippet") %>

                                 </div>
               
                              </div>
                           </header>
                           <div class="post-content">
                              <p>
              <% book.snippets.where(:approved => true).first(1).each do |snip| %>
              
              <%= raw snip.content.truncate(200) %>
              <% end %>
                          </p>
                           </div>
                           <footer class="post-footer">
                <% if can? :manage, @book %>
                 <%= link_to("Delete Book", book_path(book.id), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn-small btn-color') %>
              <% end %>
                              <%= link_to "Read More",book_path(book.id), {class: 'btn-small btn-color'}  %>
                           </footer>
                        </article>
                        <div class="blog-divider"></div>
                      <%end%>
                       
                     </div>
                  </div>
               </div>
            </div>
       

app/views/books/new.html.erb
<link href='http://fonts.googleapis.com/css?family=Mystery+Quest' rel='stylesheet' type='text/css'>
<%= render 'pages/sidebar' %>
<div class="col-md-9">
 <h2 style="font-family: 'Mystery Quest', cursive; color: #3EA5F3; font-size:400%; text-shadow: 2px 3px #000000;">The magic starts with a book title...</h2>
 <br />
<%= render 'form' %>


</div>

app/views/books/show.html.erb
<%= render 'pages/sidebar' %>

<div class="col-md-7">
<p>
	
 <h1><strong><center><%= @book.title %></strong></h1>
                           
 <p><center>
 	<i class="icon-time"></i>
    <%= @book.created_at.to_s(:create_date) %>
    <i class="icon-user"></i>
    <%= @book.user.full_name %>
    <i class="icon-tags"></i>
    <%= @count %>
    <i class="icon-comments"></i>
    <%= pluralize(@book.snippets.count, "Snippet") %>
</center></p>

         <%= render 'snippets/snippet' %>
        <%= will_paginate @snippets %>


  <%= simple_form_for [@book, @snippet] do |f| %>
        <p><%= f.input :content, label: false, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %></p>
         <%= f.button :submit, "Create Snippet", :class => "btn-primary btn-lg" %></p>
    <% end %>
 
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>