config/routes.rb
EvolvingFinal::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } 


  root to: 'pages#home'
  resources :admins
  resources :users
 
  resources :books do
     resources :snippets, :only => [:create, :edit, :update, :destroy]
  end
  

  #get 'sign_in', :to => 'users/sessions#new', :as => :new_session
  post "books/:id/activate" => "books#approve", :as => "active_book"
  post "snippets/:id/activate" => "snippets#approve", :as => "active_snippet"

  put "books/:book_id/like", to: "books#upvote", :as => "book_like"
  put "books/:book_id/dislike", to: "books#downvote", :as => "book_dislike"
 

end

app/views/layouts/_header.html.erb
<div class="wrap">
         <!-- Header Start -->
         <header id="header">
            <!-- Header Top Bar Start -->
            <div class="top-bar">
               <div class="slidedown collapse">
                  <div class="container">
                     <div class="phone-email pull-left">
                        <a href="mailto:contact@evolvingta.com"><i class="icon-envelope"></i> Email : contact@evolvingtale.com</a>
                     </div>
                     <div class="pull-right">
                        <ul class="social pull-left">
                           <li class="fa-frown-o"><a href="#"><i class="icon-facebook"></i></a></li>
                           <li class="twitter"><a href="#"><i class="icon-twitter"></i></a></li>
                           <li class="dribbble"><a href="#"><i class="icon-dribbble"></i></a></li>
                           <li class="linkedin"><a href="#"><i class="icon-linkedin"></i></a></li>
                           <li class="rss"><a href="#"><i class="icon-rss"></i></a></li>
                        </ul>
                        <div id="search-form" class="pull-right">
                           <form action="#" method="get">
                              <input type="text" class="search-text-box">
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <!-- Header Top Bar End -->
            <!-- Main Header Start -->
            <div class="main-header">
               <div class="container">
                  <!-- TopNav Start -->
                  <div class="topnav navbar-header">
                     <a class="navbar-toggle down-button" data-toggle="collapse" data-target=".slidedown">
                     <i class="icon-angle-down icon-current"></i>
                     </a> 
                  </div>
                  <!-- TopNav End -->
                  <!-- Logo Start -->
                  <div class="logo pull-left">
                     <h1>
                        <%= link_to root_path do %>
                        <img src="/assets/logo.png" alt="evolvingtale" width="125" height="60">
                        <% end %>
                     </h1>
                  </div>
                  <!-- Logo End -->
                  <!-- Mobile Menu Start -->
                  <div class="mobile navbar-header">
                     <a class="navbar-toggle" data-toggle="collapse" href=".navbar-collapse">
                     <i class="icon-reorder icon-2x"></i>
                     </a> 
                  </div>
                  <!-- Mobile Menu End -->
                  <!-- Menu Start -->
                    <div class="collapse navbar-collapse menu">
                    <ul class="nav navbar-nav sf-menu">
                     <% if user_signed_in? %>
                     <% if can? :manage, :all %>
                        <li><%= link_to "Manage", admins_path %></li>
                    <% end %>
                    <% end %>
                  <% if user_signed_in? %>
                  <% if can? :create, Book %>
                 <li><%= link_to "Create a Book", new_book_path %></li>
                 <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse Books<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "All Books", books_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Horror", books_path(:cat => "Horror") %></li>
                  <li><%= link_to "Thriller", books_path(:cat => "Thriller") %></li>
                  <li><%= link_to "Sci-Fi", books_path(:cat => "Sci-Fi") %></li>
                  <li><%= link_to "Romance", books_path(:cat => "Romance") %></li>
                  <li><%= link_to "Action", books_path(:cat => "Action") %></li>
                  <li><%= link_to "Romance", books_path(:cat => "Crime") %></li>
              
                <% else %>
                    <li><%= link_to "Browse Books", books_path %></li>
                  <% end %>
                    <% else %>
      
              <% end %>
      </ul>
 </ul>



    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
       <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                 
          
                <% else %>
                  <li><%= link_to "Login",  new_user_session_path %></li>
                  <li><%= link_to "Sign Up",  new_user_registration_path %></li>
                <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>


                  <!-- Menu End --> 
               </div>
            </div>
            <!-- Main Header End -->
         </header>
         <!-- Header End --> 

app/views/layouts/_header2.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="nav-collapse">
        <ul class="nav">
                <a class="brand" href="#">Present Ideas</a>
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Help</a></li>
                <li class="dropdown" id="accountmenu">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account Settings<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Login</a></li>
                      	<li class="dropdown-submenu">
                          <a tabindex="-1" href="#">More options</a>
                          <ul class="dropdown-menu">
                            <li><a tabindex="-1" href="#">Second level</a></li>
                            <li class="dropdown-submenu">
                              <a href="#">More..</a>
                              <ul class="dropdown-menu">
                                  <li><a href="#">3rd level</a></li>
                                  <li><a href="#">3rd level</a></li>
                              </ul>
                            </li>
                            <li><a href="#">Second level</a></li>
                            <li><a href="#">Second level</a></li>
                          </ul>
                        </li>
                        <li><a href="#">Register</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Logout</a></li>
                    </ul>
                </li>
            </ul>
        <ul class="nav pull-right">

        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Handlee' rel='stylesheet' type='text/css'>
  <title>Evolving Tale</title>
  <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  
  
</head>
<% if user_signed_in? %>
<body class="<%= controller_name %> <%= action_name %>">

<%= render 'layouts/header' %>
    
	
	      	<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">×</button>
				<%= message %>
			</div>
		<% end %>
		    
		<%= yield %>

	</div>
	</body>
	<% else %>
	<body class="bg">

  <%= render 'layouts/header' %>
 
   
	      	<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">×</button>
				<%= message %>
			</div>
		<% end %>
		<div class="container-fluid">    
		<%= yield %>
        </div>
	
	</body>
<% end %>
</html>